

import type { Model } from "../types.ts";

export const CAPGEMINI_MODELS = {
	"amazon.nova-micro-v1:0": {
		id: "amazon.nova-micro-v1:0",
		name: "amazon.nova-micro-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 5120,
	} satisfies Model<"openai-completions">,
	"amazon.nova-pro-v1:0": {
		id: "amazon.nova-pro-v1:0",
		name: "amazon.nova-pro-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 5120,
	} satisfies Model<"openai-completions">,
	"amazon.nova-lite-v1:0": {
		id: "amazon.nova-lite-v1:0",
		name: "amazon.nova-lite-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: false,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 5120,
	} satisfies Model<"openai-completions">,
	"anthropic.claude-sonnet-4-20250514-v1:0": {
		id: "anthropic.claude-sonnet-4-20250514-v1:0",
		name: "anthropic.claude-sonnet-4-20250514-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 64000,
	} satisfies Model<"openai-completions">,
	"anthropic.claude-sonnet-4-5-20250929-v1:0": {
		id: "anthropic.claude-sonnet-4-5-20250929-v1:0",
		name: "anthropic.claude-sonnet-4-5-20250929-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 64000,
	} satisfies Model<"openai-completions">,
	"anthropic.claude-haiku-4-5-20251001-v1:0": {
		id: "anthropic.claude-haiku-4-5-20251001-v1:0",
		name: "anthropic.claude-haiku-4-5-20251001-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 64000,
	} satisfies Model<"openai-completions">,
	"anthropic.claude-sonnet-4-6": {
		id: "anthropic.claude-sonnet-4-6",
		name: "anthropic.claude-sonnet-4-6",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 64000,
	} satisfies Model<"openai-completions">,
	"mistral.mistral-7b-instruct-v0:2": {
		id: "mistral.mistral-7b-instruct-v0:2",
		name: "mistral.mistral-7b-instruct-v0:2",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
	"mistral.mistral-large-2402-v1:0": {
		id: "mistral.mistral-large-2402-v1:0",
		name: "mistral.mistral-large-2402-v1:0",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
	"mistral.devstral-2-123b": {
		id: "mistral.devstral-2-123b",
		name: "mistral.devstral-2-123b",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
	"gemini-2.5-flash-lite": {
		id: "gemini-2.5-flash-lite",
		name: "gemini-2.5-flash-lite",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
	"gemini-3.5-flash": {
		id: "gemini-3.5-flash",
		name: "gemini-3.5-flash",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
	"phi-4-mini-reasoning": {
		id: "phi-4-mini-reasoning",
		name: "phi-4-mini-reasoning",
		api: "openai-completions",
		provider: "capgemini",
		baseUrl: "https://openai.generative-eu.engine.capgemini.com/v1",
		reasoning: true,
		input: ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 65536,
		maxTokens: 8192,
	} satisfies Model<"openai-completions">,
} as const;
